ARG HASH

FROM eeems/remarkable-toolchain:4.3.98-rm2 AS builder

RUN bash -e <<EOT
  export DEBIAN_FRONTEND="noninteractive"
  apt-get update
  apt-get dist-upgrade -y --no-install-recommends
  apt-get install -y --no-install-recommends \
    libyaml-dev \
    pkg-config
  apt-get clean
  rm -rf /var/lib/apt/lists/*
EOT

ARG KERNEL

RUN <<EOT
  set -e
  curl https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-${KERNEL}.tar.xz \
  | tar -xJf - -C /
  mv /linux-${KERNEL} /linux
EOT

WORKDIR /linux

COPY busybox-kernel.config .config

RUN bash -e <<EOT
  source "$(find /opt/codex -name environment-setup-*-remarkable-linux-gnueabi)"
  make -j $(nproc)
EOT

FROM scratch

COPY --from=builder /linux/arch/arm/boot/zImage /busybox-zImage

ARG HASH
LABEL hash="${HASH:?Hash missing}"
