ARG HASH

FROM alpine:latest AS codexctl

RUN apk add --no-cache curl

RUN <<EOT
  wget -q -nv -O - https://api.github.com/repos/Jayy001/codexctl/releases/latest \
  | awk -F': ' '/browser_download_url/ && /ubuntu-latest\.zip/ \
  {gsub(/"/, "", $(NF)); system("curl -LO " $(NF))}'
  unzip ubuntu-latest.zip
  rm ubuntu-latest.zip
  chmod +x codexctl
EOT

FROM debian:13-slim

RUN <<EOT
  set -e
  export DEBIAN_FRONTEND="noninteractive"
  apt-get update
  apt-get dist-upgrade -y --no-install-recommends
  apt-get install -y --no-install-recommends \
    ssh \
    socat \
    libevdev2 \
    libsdl2-2.0-0 \
    psmisc \
    util-linux
  apt-get autoremove -y
  apt-get clean
  rm -rf /var/lib/apt/lists/*
  mkdir -p /artifact
EOT

COPY --from=codexctl codexctl /usr/local/bin/
COPY --from=rootfs . /artifact/
COPY --from=kernel . /artifact/
COPY --from=busybox-kernel . /artifact/
COPY --from=busybox-initrd . /artifact/
COPY --from=busybox . /usr/local/bin/
COPY --from=bash . /usr/local/bin/

COPY --from=qemu-system-arm \
  qemu-system-arm \
  qemu-img \
  qemu-pr-helper \
  qemu-storage-daemon \
  /usr/bin/

# COPY --from=qemu-system-arm \
#   /firmware/* \
#   /usr/share/qemu/

COPY --from=qemu-system-arm \
  qemu-bridge-helper \
  /usr/libexec/

COPY --from=rm2fb \
  /rm2fb.tar.gz \
  /artifact/

COPY --from=rm2fb \
  /rm2fb-emu \
  /usr/bin/

COPY dropbear.socket rm2fb.conf /artifact/
COPY bin/. /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/entrypoint"]

ARG HASH
LABEL hash="${HASH:?Hash missing}"

RUN /usr/local/bin/busybox --list-full
