ARG HASH

FROM alpine:latest AS codexctl

RUN <<EOT
  wget https://github.com/Jayy001/codexctl/releases/download/1765093380/ubuntu-latest.zip
  unzip ubuntu-latest.zip
  rm ubuntu-latest.zip
  chmod +x codexctl
EOT

FROM debian:13-slim

RUN <<EOT
  set -e
  export DEBIAN_FRONTEND="noninteractive"
  apt-get update
  apt-get dist-upgrade -y --no-install-recommends
  apt-get install -y --no-install-recommends \
    ssh \
    socat \
    netcat-openbsd \
    libevdev2 \
    libsdl2-2.0-0 \
    psmisc \
    util-linux
  apt-get autoremove -y
  apt-get clean
  rm -rf /var/lib/apt/lists/*
  mkdir -p /artifact
EOT

COPY --from=rootfs . /artifact/
COPY --from=kernel . /artifact/
COPY --from=busybox-kernel . /artifact/
COPY --from=busybox.img . /artifact/
COPY --from=busybox . /usr/local/bin/
COPY --from=qemu-system-arm \
	qemu-system-arm \
	qemu-img \
	qemu-pr-helper \
	qemu-storage-daemon \
	/usr/bin/
# COPY --from=qemu-system-arm \
#   /firmware/* \
#   /usr/share/qemu/
COPY --from=qemu-system-arm \
	qemu-bridge-helper \
	/usr/libexec/
COPY --from=rm2fb \
	/rm2fb.tar.gz \
	/artifact/
COPY --from=rm2fb \
	/rm2fb-emu \
	/usr/bin/
COPY --from=codexctl codexctl /usr/local/bin
COPY dropbear.socket rm2fb.conf /artifact/

RUN <<EOT
  ln -s busybox /usr/local/bin/killall
  ln -s busybox /usr/local/bin/lsof
  ln -s busybox /usr/local/bin/pidof
EOT

COPY bin/* /usr/local/bin

ENTRYPOINT ["/usr/local/bin/entrypoint"]

ARG HASH
LABEL hash="${HASH:?Hash missing}"
