ARG HASH

FROM eeems/remarkable-toolchain:4.3.98-rm2 AS builder

RUN bash -e <<EOT
  export DEBIAN_FRONTEND="noninteractive"
  apt-get update
  apt-get dist-upgrade -y --no-install-recommends
  apt-get install -y --no-install-recommends \
    libyaml-dev \
    pkg-config
  apt-get clean
  rm -rf /var/lib/apt/lists/*
EOT

ARG KERNEL="${KERNEL:?KERNEL missing}"

RUN git clone \
  --branch=${KERNEL} \
  --depth=1 \
  https://github.com/reMarkable/linux.git \
  /linux


WORKDIR /linux

COPY qemu.dts /
COPY qemu.config /linux/arch/arm/configs/

RUN bash -e <<EOT
  source "$(find /opt/codex -name environment-setup-*-remarkable-linux-gnueabi)"
  mv arch/arm/boot/dts/imx7d-cl-som-imx7{,-factory}.dts
  mv /qemu.dts arch/arm/boot/dts/imx7d-cl-som-imx7.dts
  make zero-sugar_defconfig
  make qemu.config
  sed -i 's/=m/=n/' .config
EOT

RUN bash -e <<EOT
  source "$(find /opt/codex -name environment-setup-*-remarkable-linux-gnueabi)"
  make -j $(nproc)
  make -j $(nproc) imx7d-cl-som-imx7.dtb
EOT

FROM scratch

COPY --from=builder /linux/arch/arm/boot/zImage /
COPY --from=builder /linux/arch/arm/boot/dts/imx7d-cl-som-imx7.dtb /qemu.dtb

ARG HASH
LABEL hash="${HASH:?Hash missing}"
