ARG KERNEL
# ARG KERNEL_TAG

FROM eeems/remarkable-toolchain:4.3.98-rm2 AS builder

RUN bash -e <<EOT
  export DEBIAN_FRONTEND="noninteractive"
  apt-get update
  apt-get dist-upgrade -y --no-install-recommends
  apt-get install -y --no-install-recommends \
    libyaml-dev \
    pkg-config
  apt-get clean
  rm -rf /var/lib/apt/lists/*
EOT


# ARG KERNEL_TAG="${KERNEL_TAG:?KERNEL_TAG missing}"
# RUN git clone \
#   --branch=${KERNEL_TAG} \
#   --depth=1 \
#   https://github.com/reMarkable/linux.git \
#   /linux

ARG KERNEL="${KERNEL:?KERNEL missing}"

RUN <<EOT
  set -e
  curl https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-${KERNEL}.tar.xz \
  | tar -xJf - -C /
  mv /linux-${KERNEL} /linux
EOT

WORKDIR /linux

COPY qemu.dts /
COPY qemu.config /linux/arch/arm/configs/


RUN bash -e <<EOT
  source "$(find /opt/codex -name environment-setup-*-remarkable-linux-gnueabi)"
  mv arch/arm/boot/dts/imx7d-cl-som-imx7{,-factory}.dts
  mv /qemu.dts arch/arm/boot/dts/imx7d-cl-som-imx7.dts
  make imx_v6_v7_defconfig
  make qemu.config
  sed -i 's/=m/=n/' .config
EOT

RUN bash -e <<EOT
  source "$(find /opt/codex -name environment-setup-*-remarkable-linux-gnueabi)"
  make -j $(nproc)
  make -j $(nproc) imx7d-cl-som-imx7.dtb
EOT

ARG VERSION="${VERSION:?VERSION missing}"
RUN bash -e <<EOT
  source "$(find /opt/codex -name environment-setup-*-remarkable-linux-gnueabi)"
   make -j $(nproc) LOCALVERSION="-${VERSION}-rm11x"
EOT

FROM scratch

COPY --from=builder /linux/arch/arm/boot/zImage /
COPY --from=builder /linux/arch/arm/boot/dts/imx7d-cl-som-imx7.dtb /qemu.dtb
