FROM debian:13-slim as guestfs

RUN <<EOT
  set -e
  export DEBIAN_FRONTEND="noninteractive"
  apt-get update
  apt-get dist-upgrade -y --no-install-recommends
  apt-get install -y --no-install-recommends \
    qemu-utils \
    guestfish \
    linux-image-amd64 \
    libguestfs-tools
  apt-get autoremove -y
  apt-get clean
  rm -rf /var/lib/apt/lists/*
EOT

FROM guestfs AS base

COPY .shrink-image /usr/local/bin/shrink-image

RUN <<EOT
  set -e
  ln -s /bin/false /usr/local/bin/rm-is-running
  ln -s /bin/false /usr/local/bin/rm-image-path
EOT

RUN <<EOT
  set -e

  qemu-img create \
    --format qcow2 \
    --options compression_type=zstd \
    /base.qcow2 \
    8G

  guestfish --rw --blocksize=512 --add /base.qcow2 <<EOF
    run

    part-init /dev/sda mbr
    part-add /dev/sda p 2048    43007
    part-add /dev/sda p 43008   595967
    part-add /dev/sda p 595968  1148927
    part-add /dev/sda p 1148928 14942207

    mkfs vfat /dev/sda1
    mkfs ext4 /dev/sda2
    mkfs ext4 /dev/sda3
EOF
  shrink-image /base.qcow2
EOT

FROM scratch

COPY --from=base /base.qcow2 /
