ARG HASH KERNEL

FROM alpine:latest AS builder

RUN apk add --no-cache \
  build-base \
  make \
  pkgconfig \
  bzip2 \
  wget \
  cpio \
  git

RUN <<EOT
  set -e
  wget https://www.busybox.net/downloads/busybox-1.36.1.tar.bz2
  tar -xf busybox-1.36.1.tar.bz2
  rm busybox-1.36.1.tar.bz2
  mv busybox-1.36.1 /busybox
EOT

WORKDIR /busybox

COPY busybox.config .config

RUN <<EOT
  make -j$(nproc)
  make install
EOT

FROM scratch

COPY --from=builder /busybox/install/bin/busybox /

ARG HASH
LABEL hash="${HASH:?Hash missing}"
