#!/bin/sh

mkdir -p dev proc sys etc tmp mnt/script
echo "root:x:0:0:root:/root:/bin/sh" >/etc/passwd
echo "root:x:0:" >/etc/group
echo "root:::0:::::" >/etc/shadow
mount -t devtmpfs devtmpfs /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp
if [ -b /dev/mmcblk0 ]; then
  mount -o ro /dev/mmcblk0 /mnt/script
fi

ip link set lo up
ip link set eth0 up
udhcpc

dropbear -REB -W 524288

dmesg -n 1

if [ -x /mnt/script/init ]; then
  /mnt/script/init
else
  ${1:-/bin/sh}
fi

if mountpoint -q /mnt; then
  umount /mnt
fi

poweroff -f
