#!/bin/sh
echo "[init] Mounting filesystems..."
mount -t devtmpfs devtmpfs /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts

mv_blk() {
  if [ $# -ne 2 ]; then
    echo "Error: mv_blk called with incorrect number of arguments" >/dev/stderr
    return
  fi
  if [ ! -b "/dev/$1" ]; then
    return
  fi
  echo "[init] Renaming /dev/$1 -> /dev/$2"
  mv "/dev/$1" "/dev/$2"
  for p in "/dev/$1"[0-9]*; do
    if [ -e "$p" ]; then
      part_num=$(echo "$p" | sed "s|/dev/$1||")
      from="/dev/$1$part_num"
      to="/dev/${2}p$part_num"
      echo "Renaming $from -> $to"
      mv "$from" "$to"
    fi
  done
}
mv_blk vda mmcblk0
mv_blk vdb mmcblk1
mv_blk vdc mmcblk2
unset -f mv_blk

mount -a

if [ -b /dev/mmcblk0 ] && [ ! -b /dev/mmcblk0p1 ]; then
  mkdir -p /mnt/script
  if ! mount -o ro /dev/mmcblk0 /mnt/script; then
    rmdir /mnt/script
  fi
fi

echo "[init] Starting network..."
ip link set lo up
ip link set eth0 up
udhcpc

echo "[init] Starting dropbear..."
dropbear -REB -W 524288

dmesg -n 1

if [ -x /mnt/script/init ]; then
  echo "[init] Starting /mnt/script/init..."
  /mnt/script/init "$@"
else
  cmd=${1:-/bin/sh}
  if [ $# -gt 0 ]; then
    shift
  fi
  echo "[init] Starting $cmd..."
  $cmd "$@"
fi
echo "[init] Sending SIGTERM to all child processes..."
killall5 -15
wait=10
while pgrep $$ >/dev/null && [ $wait -gt 0 ];do
  sleep 0.1
  wait=$((wait - 1))
done
echo "[init] Sending SIGKILL to all child processes..."
killall5 -9
echo "[init] Syncing disks..."
sync
sync
echo "[init] Disabling swap..."
swapoff -a
echo "[init] Unmounting all filesystems..."
umount -a -r
poweroff -f
