#!/bin/bash
set -e
_D="$(dirname "$(dirname "$(readlink -f "${0}")")")"
export ROOTDIR="/tmp/rm-qemu-share/rm-qemu"
export DATADIR="$HOME/.local/share/rm-qemu"
export CACHEDIR="$HOME/.cache/rm-qemu/cache"
export STATEDIR="$HOME/.cache/rm-qemu/state"
mkdir -p "$DATADIR" "$CACHEDIR" "$STATEDIR"
export PATH="$_D/bin:${PATH}"
export RM_EMU_PORT=${RM_EMU_PORT:-$(get-free-port)}
export RM_SSH_PORT=${RM_SSH_PORT:-$(get-free-port "${RM_EMU_PORT}")}
if [ $# -eq 1 ] && [[ "$1" == "--debug" ]]; then
  cd "$_D"
  exec bash -l </dev/stdin >/dev/stdout 2>/dev/stderr
fi
errors=()
if ! command -v qemu-img >/dev/null; then
  errors+=("Unable to find qemu-img command, please install qemu-img")
fi
if ! command -v qemu-system-arm >/dev/null; then
  errors+=("Unable to find qemu-system-arm command, please install qemu-system-arm")
fi
if ! command -v ssh >/dev/null; then
  errors+=("Unable to find ssh command, please install ssh")
fi
if ! command -v ssh-keygen >/dev/null; then
  errors+=("Unable to find ssh-keygen command, please install ssh")
fi
if ! command -v pidof >/dev/null; then
  errors+=("Unable to find pidof command, please install pidof")
fi
if ! command -v killall >/dev/null; then
  errors+=("Unable to find killall command, please install killall")
fi
if [ ${#errors[@]} -gt 0 ]; then
  echo "Errors found:"
  for e in "${errors[@]}"; do
    echo "  $e"
  done
  exit 1
fi
exec entrypoint "$@" </dev/stdin >/dev/stdout 2>/dev/stderr
