#!/bin/bash
set -e
KERNEL=${KERNEL:?KERNEL environment variable must be specified}
APPDIR="rm-qemu.AppDir"
rm -rf "${APPDIR}"

# Copy initial files
mkdir -p \
  "${APPDIR}/bin" \
  "$APPDIR/share/rm-qemu/artifact"
cp \
  appimage-entrypoint \
  "${APPDIR}/bin"

# Import some helper programs that can be run with sharun
APPDIR="${APPDIR}" \
  DESKTOP="rm-qemu.desktop" \
  ICON=rm-qemu.png \
  MAIN_BIN=appimage-entrypoint \
  _tmp_bin=rm-qemu-bin \
  _tmp_lib=rm-qemu-lib \
  _tmp_share=rm-qemu-share \
  quick-sharun \
  /usr/bin/{nc,rm2fb-emu,socat} \
  /usr/bin/qemu-{img,system-arm,pr-helper,storage-daemon} \
  /usr/libexec/qemu-bridge-helper \
  /usr/share/qemu/

_hook="${APPDIR}/bin/path-mapping-hardcoded.src.hook"
if [ -f "$_hook" ]; then
  sed -i -e 's|_tmp_bin=""|_tmp_bin="rm-qemu-bin"|' "$_hook"
  sed -i -e 's|_tmp_lib=""|_tmp_lib="rm-qemu-lib"|' "$_hook"
  sed -i -e 's|_tmp_share=""|_tmp_share="rm-qemu-share"|' "$_hook"
else
  cat <<-'EOF' >"$_hook"
  #!/bin/sh
  _tmp_bin="rm-qemu-bin"
  _tmp_lib="rm-qemu-lib"
  _tmp_share="rm-qemu-share"

  if ! command -v ln 1>/dev/null; then
      >&2 echo "path-mapping-hardcoded: ERROR we cannot make symlinks"
      >&2 echo "because command 'ln' is missing from the system! Aborting..."
      exit 1
  fi

  if [ -n "$_tmp_bin" ]; then
      ln -sfn "$APPDIR"/bin /tmp/"$_tmp_bin"
  fi
  if [ -n "$_tmp_lib" ]; then
      ln -sfn "$APPDIR"/lib /tmp/"$_tmp_lib"
  fi
  if [ -n "$_tmp_share" ]; then
      ln -sfn "$APPDIR"/share /tmp/"$_tmp_share"
  fi
EOF
  chmod +x "$_hook"
fi

# Copy static files
cp -r /artifact/* "$APPDIR/share/rm-qemu/artifact"
cp \
  /usr/local/bin/* \
  "${APPDIR}/bin"

# Create AppImage
APPDIR="${APPDIR}" \
  VERSION="kernel-${KERNEL}" \
  uruntime2appimage
