#!/bin/bash
set -e
tag=${1:?Tag is missing}
shift
echo "Checking $tag"
hash=${1:?Expected hash is missing}
shift
local=$(podman inspect "$tag" --format='{{ .Labels.hash }}' 2>/dev/null || true)
if [[ "$hash" == "$local" ]]; then
  echo "Skipped as local hash matches"
  if [ ! -f .image-marker ];then
    touch .image-marker
  fi
  exit
fi
remote=$(skopeo inspect "docker://$tag" --format='{{ .Labels.hash }}' 2>/dev/null || true)
if [[ "$hash" == "$remote" ]]; then
  echo "Remote hash matches"
  podman pull "$tag"
  touch .image-marker
  exit
fi
echo "Hash: $hash"
echo "Local: $local"
echo "Remote: $remote"
podman build \
  --pull=missing \
  --tag="$tag" \
  "--label=hash=$hash" \
  "$@" \
  .
touch .image-marker
