#!/bin/bash
set -e
tag=${1:?}
shift
echo "Checking $tag"
local=${2:?}
shift
image=$(podman inspect $tag --format='{{ .Labels.hash }}' 2>/dev/null)
if [[ "$local" == "$image" ]];then
  echo "Skipped as hash matches"
  exit
fi
remote=$(skopeo inspect docker://$tag --format='{{ .Labels.hash }}' 2>/dev/null)
if [[ "$local" == "$image" ]];then
  podman pull $tag
  exit
fi
podman build \
  --pull=missing \
  --tag=$tag \
  "--build-arg=HASH=$local" \
  "$@" \
  .
