#!/bin/bash
set -e
tag=${1:?Tag is missing}
shift
echo "Checking $tag"
hash=${1:?Expected hash is missing}
shift
local=$(podman inspect "$tag" --format='{{ .Labels.hash }}' 2>/dev/null || true)
if [[ "$hash" == "$local" ]]; then
  echo "Skipped as hash matches"
  exit
fi
remote=$(skopeo inspect "docker://$tag" --format='{{ .Labels.hash }}' 2>/dev/null || true)
if [[ "$hash" == "$remote" ]]; then
  podman pull "$tag"
  exit
fi
echo "Hash: $hash"
echo "Local: $local"
echo "Remote: $remote"
podman build \
  --pull=missing \
  --tag="$tag" \
  "--build-arg=HASH=$hash" \
  "$@" \
  .
